### ISSUE TITLE
Empty repo, three forks : ) And a promising name.

### ISSUE THREAD

**Issue by alexeyev** [src-d/ast2vec#7]
¡buenas tardes!

Just wondering what this is going to be. Is there a paper on what you are going to do?

Something like this?
https://pdfs.semanticscholar.org/5260/66e8c1007dd526eb4a7b89a925b95c6564f5.pdf

Thanks!

**Comment by vmarkovtsev** [comment]
Hey!

No paper exists ATM. In a few words, we do "word2vec" on source code identifiers and many other things besides. We base on [Babelfish](https://doc.bblf.sh/)'s UASTs. [vecino](https://github.com/src-d/vecino) finds similar GitHub repositories and uses ast2vec as the engine. Currently, we are preparing ast2vec for the release, uploading the models, ensuring that the training pipeline works for everybody, writing manuals, etc. The repo is not empty; we follow the git flow and work in [develop(https://github.com/src-d/ast2vec/tree/develop).

We will be happy to answer your questions in our [Slack community channel](http://sourced.tech/) - everybody can register.

**Comment by alexeyev** [comment]
> we follow the git flow and work in develop branch

Oops.

Cool stuff, thanks!
