### ISSUE TITLE
pip3 install failure: missing libxml

### ISSUE THREAD

**Issue by asah** [src-d/ast2vec#98]
Ubuntu 16.04.3

pip3 install ast2vec

    In file included from bblfsh/libuast/uast.c:2:0:
    bblfsh/libuast/uast_private.h:8:25: fatal error: libxml/tree.h: No such file or directory
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

"sudo apt-get install libxml2-dev" appears to fix this.

**Comment by vmarkovtsev** [comment]
Thanks! I will include this into the readme. We've got the complete dependecnies list in [.travis.yml](https://github.com/src-d/ast2vec/blob/master/.travis.yml)
